// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Server.Data;

#nullable disable

namespace MyBudget.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230206022415_TransTypeSeeding")]
    partial class TransTypeSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBudget.Shared.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Debit")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Debit = false,
                            Description = "This is a Deposit Transation (+)",
                            TypeName = "Deposit"
                        },
                        new
                        {
                            Id = 2,
                            Debit = true,
                            Description = "This is a Paymenmt Transation (-)",
                            TypeName = "Payment"
                        },
                        new
                        {
                            Id = 3,
                            Debit = true,
                            Description = "This is a Withdrawl Payment Transation (-)",
                            TypeName = "CashWithdrawl"
                        },
                        new
                        {
                            Id = 4,
                            Debit = false,
                            Description = "This is a Withdrawl Transation (+)",
                            TypeName = "CashDep"
                        },
                        new
                        {
                            Id = 5,
                            Debit = true,
                            Description = "This is a Credit Card Paymenmt Transation (-)",
                            TypeName = "CCPayment"
                        },
                        new
                        {
                            Id = 6,
                            Debit = false,
                            Description = "This is a Salary Transation (+)",
                            TypeName = "Payroll"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
